version: '3.7'
volumes:
  db_volume:


services:
  php:
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - '8000:8000'
  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - db_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel